// <auto-generated />
using System;
using DXStats.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DXStats.Migrations
{
    [DbContext(typeof(DxStatsDbContext))]
    partial class DxStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.3");

            modelBuilder.Entity("DXStats.Domain.Entity.Coin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            Id = "ABS"
                        },
                        new
                        {
                            Id = "AEX"
                        },
                        new
                        {
                            Id = "AGM"
                        },
                        new
                        {
                            Id = "AMS"
                        },
                        new
                        {
                            Id = "APR"
                        },
                        new
                        {
                            Id = "ATB"
                        },
                        new
                        {
                            Id = "AUS"
                        },
                        new
                        {
                            Id = "BAD"
                        },
                        new
                        {
                            Id = "BAY"
                        },
                        new
                        {
                            Id = "BCH"
                        },
                        new
                        {
                            Id = "BCZ"
                        },
                        new
                        {
                            Id = "BIT"
                        },
                        new
                        {
                            Id = "BITG"
                        },
                        new
                        {
                            Id = "BLAST"
                        },
                        new
                        {
                            Id = "BLOCK"
                        },
                        new
                        {
                            Id = "BSD"
                        },
                        new
                        {
                            Id = "BTC"
                        },
                        new
                        {
                            Id = "BTDX"
                        },
                        new
                        {
                            Id = "BTX"
                        },
                        new
                        {
                            Id = "BZX"
                        },
                        new
                        {
                            Id = "CARE"
                        },
                        new
                        {
                            Id = "CDZC"
                        },
                        new
                        {
                            Id = "CHC"
                        },
                        new
                        {
                            Id = "CHI"
                        },
                        new
                        {
                            Id = "CHN"
                        },
                        new
                        {
                            Id = "CIV"
                        },
                        new
                        {
                            Id = "CNMC"
                        },
                        new
                        {
                            Id = "COLX"
                        },
                        new
                        {
                            Id = "CRAVE"
                        },
                        new
                        {
                            Id = "CRW"
                        },
                        new
                        {
                            Id = "D"
                        },
                        new
                        {
                            Id = "DASH"
                        },
                        new
                        {
                            Id = "DGB"
                        },
                        new
                        {
                            Id = "DIN"
                        },
                        new
                        {
                            Id = "DIVI"
                        },
                        new
                        {
                            Id = "DMD"
                        },
                        new
                        {
                            Id = "DOGE"
                        },
                        new
                        {
                            Id = "DOGEC"
                        },
                        new
                        {
                            Id = "DSR"
                        },
                        new
                        {
                            Id = "DVT"
                        },
                        new
                        {
                            Id = "DYN"
                        },
                        new
                        {
                            Id = "ECA"
                        },
                        new
                        {
                            Id = "EMC"
                        },
                        new
                        {
                            Id = "EMC2"
                        },
                        new
                        {
                            Id = "ENT"
                        },
                        new
                        {
                            Id = "FAIR"
                        },
                        new
                        {
                            Id = "FGC"
                        },
                        new
                        {
                            Id = "FJC"
                        },
                        new
                        {
                            Id = "FLO"
                        },
                        new
                        {
                            Id = "GALI"
                        },
                        new
                        {
                            Id = "GBX"
                        },
                        new
                        {
                            Id = "GEEK"
                        },
                        new
                        {
                            Id = "GIN"
                        },
                        new
                        {
                            Id = "GLC"
                        },
                        new
                        {
                            Id = "GMCN"
                        },
                        new
                        {
                            Id = "GXX"
                        },
                        new
                        {
                            Id = "HASH"
                        },
                        new
                        {
                            Id = "HATCH"
                        },
                        new
                        {
                            Id = "HLM"
                        },
                        new
                        {
                            Id = "HTML"
                        },
                        new
                        {
                            Id = "INN"
                        },
                        new
                        {
                            Id = "IOP"
                        },
                        new
                        {
                            Id = "IXC"
                        },
                        new
                        {
                            Id = "JEW"
                        },
                        new
                        {
                            Id = "JIYOX"
                        },
                        new
                        {
                            Id = "KLKS"
                        },
                        new
                        {
                            Id = "KYDC"
                        },
                        new
                        {
                            Id = "KZC"
                        },
                        new
                        {
                            Id = "LBC"
                        },
                        new
                        {
                            Id = "LPC"
                        },
                        new
                        {
                            Id = "LTC"
                        },
                        new
                        {
                            Id = "LUX"
                        },
                        new
                        {
                            Id = "LYNX"
                        },
                        new
                        {
                            Id = "MAC"
                        },
                        new
                        {
                            Id = "MERGE"
                        },
                        new
                        {
                            Id = "MLM"
                        },
                        new
                        {
                            Id = "MNP"
                        },
                        new
                        {
                            Id = "MNX"
                        },
                        new
                        {
                            Id = "MONA"
                        },
                        new
                        {
                            Id = "MRX"
                        },
                        new
                        {
                            Id = "MUE"
                        },
                        new
                        {
                            Id = "N8V"
                        },
                        new
                        {
                            Id = "NIX"
                        },
                        new
                        {
                            Id = "NMC"
                        },
                        new
                        {
                            Id = "NOR"
                        },
                        new
                        {
                            Id = "NORT"
                        },
                        new
                        {
                            Id = "NYEX"
                        },
                        new
                        {
                            Id = "NYX"
                        },
                        new
                        {
                            Id = "ODIN"
                        },
                        new
                        {
                            Id = "OHMC"
                        },
                        new
                        {
                            Id = "OPCX"
                        },
                        new
                        {
                            Id = "ORE"
                        },
                        new
                        {
                            Id = "PAC"
                        },
                        new
                        {
                            Id = "PHL"
                        },
                        new
                        {
                            Id = "PHR"
                        },
                        new
                        {
                            Id = "PIVX"
                        },
                        new
                        {
                            Id = "POLIS"
                        },
                        new
                        {
                            Id = "PURA"
                        },
                        new
                        {
                            Id = "QBIC"
                        },
                        new
                        {
                            Id = "QTUM"
                        },
                        new
                        {
                            Id = "RPD"
                        },
                        new
                        {
                            Id = "RVN"
                        },
                        new
                        {
                            Id = "SCC"
                        },
                        new
                        {
                            Id = "SCN"
                        },
                        new
                        {
                            Id = "SCRIBE"
                        },
                        new
                        {
                            Id = "SEND"
                        },
                        new
                        {
                            Id = "SEQ"
                        },
                        new
                        {
                            Id = "SIB"
                        },
                        new
                        {
                            Id = "SPK"
                        },
                        new
                        {
                            Id = "STAK"
                        },
                        new
                        {
                            Id = "SUB1X"
                        },
                        new
                        {
                            Id = "SYNX"
                        },
                        new
                        {
                            Id = "SYS"
                        },
                        new
                        {
                            Id = "TRB"
                        },
                        new
                        {
                            Id = "TRC"
                        },
                        new
                        {
                            Id = "UFO"
                        },
                        new
                        {
                            Id = "UNO"
                        },
                        new
                        {
                            Id = "VIA"
                        },
                        new
                        {
                            Id = "VITAE"
                        },
                        new
                        {
                            Id = "VIVO"
                        },
                        new
                        {
                            Id = "VSX"
                        },
                        new
                        {
                            Id = "VTC"
                        },
                        new
                        {
                            Id = "WGR"
                        },
                        new
                        {
                            Id = "XC"
                        },
                        new
                        {
                            Id = "XLR"
                        },
                        new
                        {
                            Id = "XMCC"
                        },
                        new
                        {
                            Id = "XMY"
                        },
                        new
                        {
                            Id = "XN"
                        },
                        new
                        {
                            Id = "XSN"
                        },
                        new
                        {
                            Id = "XVG"
                        },
                        new
                        {
                            Id = "XZC"
                        },
                        new
                        {
                            Id = "ZNZ"
                        });
                });

            modelBuilder.Entity("DXStats.Domain.Entity.DayCompletedOrders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoinId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("DayCompletedOrders");
                });

            modelBuilder.Entity("DXStats.Domain.Entity.DayVolume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BLOCK")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoinId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustomCoin")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfTrades")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("USD")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("DayVolumes");
                });

            modelBuilder.Entity("DXStats.Domain.Entity.Snapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("DXStats.Domain.Entity.DayCompletedOrders", b =>
                {
                    b.HasOne("DXStats.Domain.Entity.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId");

                    b.HasOne("DXStats.Domain.Entity.Snapshot", "Snapshot")
                        .WithMany("DayCompletedOrders")
                        .HasForeignKey("SnapshotId");
                });

            modelBuilder.Entity("DXStats.Domain.Entity.DayVolume", b =>
                {
                    b.HasOne("DXStats.Domain.Entity.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId");

                    b.HasOne("DXStats.Domain.Entity.Snapshot", "Snapshot")
                        .WithMany("DayVolumes")
                        .HasForeignKey("SnapshotId");
                });
#pragma warning restore 612, 618
        }
    }
}
