
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: blockdxtwitterbot
  name: blockdxtwitterbot
  namespace: luciendev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: blockdxtwitterbot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: blockdxtwitterbot
    spec:
      containers:
      - image: PLACEHOLDER_IMAGE_LOCATION
        imagePullPolicy: Always
        name: blockdxtwitterbot
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30