apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      run: dxstatsbot
    name: dxstatsbot
    namespace: luciendev
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: dxstatsbot
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: dxstatsbot
      spec:
        containers:
        - image: PLACEHOLDER_IMAGE_LOCATION
          imagePullPolicy: Always
          name: dxstatsbot
          env:
          - name: DATABASE_DIR
            value: /usr/db
          - name: Twitter:consumerKey
            value: TWITTER_CONSUMER_KEY
          - name: Twitter:consumerSecret
            value: TWITTER_CONSUMER_SECRET
          - name: Twitter:userAccessToken
            value: TWITTER_USER_ACCESS_TOKEN
          - name: Twitter:userAccessSecret
            value: TWITTER_USER_ACCESS_SECRET
          - name: Discord:token
            value: DISCORD_TOKEN 
          - name: Discord:channelId
            value: "DISCORD_CHANNEL_ID"
          ports:
          - containerPort: 8090
            protocol: TCP
          volumeMounts:
          - name: sqlite-volume
            mountPath: /usr/db
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: sqlite-volume
          persistentVolumeClaim:
            claimName: sqlite-pvc
- apiVersion: v1
  kind: Service
  metadata:
    name: dxstatsbot
    namespace: luciendev
  spec:
    ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
      run: dxstatsbot
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
