apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc            # 1
  namespace: luciendev
spec:
  accessModes:
    - ReadWriteOnce           # 2
  resources:
    requests:
      storage: 4Gi            # 3