name: Build and deploy to AKS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Jberlinsky AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Find and Replace deployment twitter consumer key
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: TWITTER_CONSUMER_KEY
          replace: ${{ secrets.TWITTER_CONSUMER_KEY }}
          
      - name: Find and Replace deployment twitter consumer secret
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: TWITTER_CONSUMER_SECRET
          replace: ${{ secrets.TWITTER_CONSUMER_SECRET }}
         
      - name: Find and Replace deployment twitter user access token
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: TWITTER_USER_ACCESS_TOKEN
          replace: ${{ secrets.TWITTER_USER_ACCESS_TOKEN }}
          
      - name: Find and Replace deployment twitter user access secret
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: TWITTER_USER_ACCESS_SECRET
          replace: ${{ secrets.TWITTER_USER_ACCESS_SECRET }}
          
      - name: Find and Replace deployment discord token
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: DISCORD_TOKEN
          replace: ${{ secrets.DISCORD_TOKEN }}
          
      - name: Find and Replace deployment discord token
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: DISCORD_CHANNEL_ID
          replace: ${{ secrets.DISCORD_CHANNEL_ID }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1      
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
         
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ./DXStats/Dockerfile
          pull: true
          push: true
          cache-from: "type=registry,ref=lucienmartijn/dxstats:${{ github.sha }}"
          cache-to: type=inline
          tags: "lucienmartijn/dxstats:${{ github.sha }}"
          
      - name: Find and Replace deployment manifest
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: PLACEHOLDER_IMAGE_LOCATION
          replace:  lucienmartijn/dxstats:${{ github.sha }}
          
        
      - name: Deploy Docker Image
        uses: Jberlinsky/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: -n luciendev apply -f ./DXStats/deployment.yml
